language: java

install: /bin/true

jdk:
  - oraclejdk8

env:
    global:
        # CODACY_PROJECT_TOKEN=<secret...>
        - secure: "53deee4137a4471ba43c018379f5c8f5"

before_install:
  - gradle wrapper
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

before_script:
  - wget https://services.gradle.org/distributions/gradle-2.14-bin.zip
  - unzip gradle-2.14-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14
  - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml